apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::253729043694:role/SEOUL-MSS-SOC1-EKS-WORKER
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::253729043694:role/SEOUL-MSS-SOC1-BASTION
      username: iam_role_bastion
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::253729043694:user/changyu.seon
      username: changyu.seon
      groups:
        - system:masters