nameOverride: gitlab

# Values for gitlab/gitlab chart on GKE
# ref. https://blog.dbi-services.com/deploy-gitlab-on-kubernetes-using-helm/
global:
  edition: ce
  hosts:
    domain: bespin-mss.com
    hostSuffix: dz
certmanager-issuer:
  email: changyu.seon@bespinglobal.com
