nginx-ingress:
  nameOverride: nginx-ingress-nodeport
  controller:
    replicaCount: 2
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    autoscaling:
      enabled: true
      maxReplicas: 9
      minReplicas: 3
      targetCPUUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 60
    config:
      use-forwarded-headers: "true"
      log-format-escape-json: "true"
      log-format-upstream: '{"timestamp": "$time_iso8601", "cluster": "soc1", "requestID": "$req_id", "httpRequest": {"timeLocal": "$time_local", "httpReferer": "$http_referer", "requestMethod": "$request_method", "host": "$host", "requestUri": "$request_uri", "status": $status, "requestTime": $request_time, "bodyBytesSent": $body_bytes_sent, "requestSize": $request_length, "proxyUpstreamName": "$proxy_upstream_name", "upstreamStatus": $upstream_status, "upstreamAddr": "$upstream_addr", "upstreamResponseSize": $upstream_response_length, "httpUserAgent": "$http_user_agent","remoteAddr": "$remote_addr", "remoteUser": "$remote_user", "upstreamResponseTime": $upstream_response_time, "serverProtocol": "$server_protocol"}}'
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      type: NodePort
      nodePorts:
        http: 32000
      targetPorts:
        http: http
    stats:
      enabled: true
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"
