apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: soc1:sockshop:develop
  namespace: sockshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: soc1:develop
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: jim.park
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: anna.goo

