apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: soc1:sockshop:deploy
  namespace: sock-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: soc1:deploy
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alice.kim
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob.choi
